### ISSUE TITLE
visuele hiërarchie

### ISSUE THREAD

**Issue by kosterm14** [moonlightlizaa/connect-your-tribe-squad-page#3]
![image](https://user-images.githubusercontent.com/61830362/220078825-dbdf7812-7232-4d59-b013-477f3765d3f5.png)

Misschien de tekst grootte "FDND Squad A" veranderen om er meer nadruk op te leggen

**Comment by moonlightlizaa** [comment]
Goed idee. Ik zou het meenemen naar de bouwfase 🌷🌷🌷
